### ISSUE TITLE
Dedicated Unnamed Default Graph vs. Union Default Graph

### ISSUE THREAD

**Issue by elf-pavlik** [rdfjs/data-model-spec#117]
I just recalled this conversation https://gitter.im/rdfjs/Representation-Task-Force?at=581b4cc9c2f2cf7275c5f43b and decided to capture it as issue to have clear resolution.

Looking at http://depressiverobot.com/2015/07/29/sparql-datasets.html
> To my knowledge, current RDF databases use two different approaches for the default dataset where both contain all the available named graphs and:
>* an unnamed default graph which holds its own information (**Dedicated Unnamed Default Graph**);
>* an unnamed default graph which is the RDF merge of all named graphs (the so called **Union Default Graph**).

Current RDF/JS draft seems to take Dedicated Unnamed Default Graph approach in representing datasets, at the same time rdflib.js might take Union Default Graph approach (maybe @timbl or @dmitrizagidulin could help to clarify).

Resolution of this issue should ensure that everyone involved and their implementations use the same approach to *unnamed default graph*

**Comment by bergos** [comment]
+1 `unnamed default graph`, a `union default graph` can be implemented with a wrapper and minimal overhead.  `union default graph` as the default behavior would require client side filtering to change it to `unnamed default graph`. Also `unnamed default graph` behavior for subject, predicate, object and graph would be the same.

**Comment by elf-pavlik** [comment]
@timbl @RubenVerborgh maybe two of you would have a chance to discuss it at MIT and make sure that we all stay on the same page in this matter?

**Comment by elf-pavlik** [comment]
It looks like we find also find `unnamed default graph` approach in SPARQL 1.1 Update spec
https://www.w3.org/TR/sparql11-update/#def_graphstore
> ## Definition: Graph Store
>  A Graph Store GS is a mutable container of RDF graphs. It has one unnamed (default) slot and zero or more named slots. The unnamed slot holds an RDF graph; each named slot is a pair of a graph and an associated IRI. The Graph Store can be viewed as a mutable RDF Dataset.

>GS = {DG, (iri1, G1), ... , (irin, Gn) }

> where
>* the default graph DG is the RDF graph associated with the unnamed slot
>* n ≥ 0 and for each 1 ≤ i ≤ n, Gi is an RDF graph associated with the named slot identified by IRI irii
>* all IRIs are distinct, i.e., i≠j implies irii≠irij

**Comment by timbl** [comment]
I was disappointed in this split.   In rdflib.js always been very easy and often the normal thing to do to query all the loaded data.  To do that you just leave the 4th part out, undefined.  This is using the quadstore as a triple store, which is a very important use case.  In the particular but important  case in which all the data you have loaded is trusted, the most powerful thing is to query it all.   So the union is very valuable to be a default.  And in JS, you pass undefined to get the default.  The attitude the SPAQL folks took above is not appropriate for a general purpose in-memory quadstore. If you had to search the triple sore by passing  `new DefaultGraph()` that would be massively unacceptable.

**Comment by elf-pavlik** [comment]
from https://github.com/linkeddata/rdflib.js/pull/230#issuecomment-393086800
> @timbl: rdflib.js uses the union interpretation of default graph. And null or undefined may be used as the default graph name. store.statementsMatching(s,p,o) gives you all the quads matching the triple pattern s p o no matter where they were loaded from.

I think `match()` defined in http://rdf.js.org/#source-interface should behave just as in rdflib.js, plus if someone want's to query just the `Dedicated Unnamed Default Graph` one can pass a `DefaultGraph` as 4th paramenter. Maybe @bergos and @RubenVerborgh could confirm or correct my understanding of how current draft defines `match()`, especially when called with `g` omitted.

**Comment by blake-regalia** [comment]
I think #124 is also related to this

**Comment by elf-pavlik** [comment]
Created PR #154
