### ISSUE TITLE
Add DataFactory method to create from existing term

### ISSUE THREAD

**Issue by RubenVerborgh** [rdfjs/data-model-spec#137]
We want to consider adding a method to `DataFactory` that takes a `Term`-shaped object (from _any_ library) as input, and outputs a `Term` (from the library of the `DataFactory`) that `equals` it.

This can be used to convert a `Term` from one RDF/JS implementation to another.

**Comment by rubensworks** [comment]
For consistency, we may also want add a similar method for converting `Quad` objects.

**Comment by elf-pavlik** [comment]
I could make PR for `DataFactory#clone()`

```webidl
(Term or Quad) clone((Term or Quad) other)
```

I think in this case we don't allow `undefined` or `null`

**Comment by rubensworks** [comment]
@elf-pavlik I would propose creating separate methods for cloning terms and quads (`cloneTerm`, `cloneQuad`). Implementations may otherwise become too complicated for determining the argument type.

**Comment by RubenVerborgh** [comment]
fromTerm/fromQuad?

**Comment by bergos** [comment]
👎  for `.clone()`, as this could be interpreted as a clone function of the factory itself. It doesn't make sense now, but maybe in the future we have an additional spec (Prefix + CURIE support which turns the DataFactory into an environment) were having multiple instance of the DataFactory makes more sense.

I favor `fromTerm` and `fromQuad` a little bit over `cloneTerm` and `cloneQuad`. `from*` indicates much stronger that new instances by the DataFactory are created and not that somehow the constructor of the given Term/Quad is used.

**Comment by elf-pavlik** [comment]
`fromTerm` & `fromQuad` SGTM, if no one else makes PR today/tomorrow I'll submit one on Wednesday

**Comment by elf-pavlik** [comment]
PR #158

**Comment by awwright** [comment]
Sorry I just noticed this, but I'm curious... Why not pass a plain object to the Term or Quad functions directly?

**Comment by elf-pavlik** [comment]
As I replied on https://gitter.im/rdfjs/public?at=5cb48398c55bd14d35ebcf88 single factory object makes it much easier to pass it around. Spec only defines methods on the factory and doesn't define any constructors for specific terms.
