### ISSUE TITLE
URL for the spec

### ISSUE THREAD

**Issue by bergos** [rdfjs/data-model-spec#138]
The spec is currently hosted at http://rdf.js.org/. We are also working already on the [Dataset spec](https://rdf.js.org/dataset-spec/dataset-spec.html). To have more future prove URLs, I propose to create a different repository, which will be used to host the start page. On the start page we can list all specs, libraries, additional documentation, etc.

**Comment by bergos** [comment]
That would also mean that the URL would change to the repository name, which would be http://rdf.js.org/representation-task-force/ at the moment. We should give the repo a better name, matching to the scope of the spec. It contains the Data Model + Stream interfaces. Let's just skip the Stream part from the repo name and just call it `data-model-spec`.

**Comment by RubenVerborgh** [comment]
+1

**Comment by bergos** [comment]
Please +1 in the next 3 days if you agree or leave a comment if you disagree. I will rename the repo then and create a new repo for the start page.

**Comment by elf-pavlik** [comment]
if you use index.html in those repos, will we get just

* https://rdf.js.org/data-model-spec (redirecting to add following /)
* https://rdf.js.org/dataset-spec (redirecting to add following /)

?

**Comment by vhf** [comment]
@elf-pavlik Yes that's how it works as long as we have:

    https://github.com/rdfjs/rdfjs.github.io/blob/master/CNAME
                             ^^^^^^^^^^^^^^^             ^^^^^

and github pages enabled in the repos

**Comment by elf-pavlik** [comment]
@bergos https://github.com/rdfjs/rdfjs.github.io could become the index (home) page

**Comment by elf-pavlik** [comment]
I don't want to get into bikeshedding but maybe we should just call the first spec `data-factory-spec`, keep the second `dataset-spec` and come up with name for stream interfaces possibly even splitting `source-sink-spec` from `store-spec` which may include RegExp and/or filtering.

https://github.com/rdfjs/data-model/ actually exports Data Factory so naming spec and module `data-factory` makes more sense to me.

**Comment by RubenVerborgh** [comment]
Let's not make it too complex people, or no one's gonna use it. `factory` by itself is already _extremely_ heavy for JavaScript standards, let's not emphasize.

**Comment by bergos** [comment]
I think `data-model` is more understandable than `data-factory`. Also it's more important what your factory builds and Data Model objects sounds good to me for `Term` and `Quad` objects. The Dataset spec also defines a factory and that's also what the package exports. That could be also the case for a Prefix spec. So we may end up with a lot of `-factory` repos if we add factory to all of them.

**Comment by elf-pavlik** [comment]
ok `data-model` sorry for distraction

**Comment by blake-regalia** [comment]
I actually find `data-factory` easier to understand but maybe I am in the minority :)

**Comment by elf-pavlik** [comment]
Should we rename this repo to `data-model-spec` and rename `interface-spec.html` to `index.html` so that we have it available on https://rdf.js.org/data-model-spec ?

**Comment by bergos** [comment]
I made a PR to rename the file to `index.html` #155 . I think it's not a problem to rename the repo already now. The new start page for rdf.js.org is in progress. I should be able to make a PR till tomorrow.
