### ISSUE TITLE
Move stream interfaces into separate spec

### ISSUE THREAD

**Issue by bergos** [rdfjs/data-model-spec#156]
Maybe we should split the current spec into `data-model-spec` and `stream-spec`. Having two separate specs would fit better into the structure like we have it now with the `dataset-spec`. Also it would be easier to make releases. Having less issues would help to get a better overview of the current state of the spec.

Let's vote: 👍 for a separate `stream-spec` 👎 to keep it like it is now.

**Comment by RubenVerborgh** [comment]
I'm fine with it; we just need a good overview page then though explaining how everything fits together.

**Comment by elf-pavlik** [comment]
:+1: 
We would transfer those issues to that repo: https://github.com/rdfjs/representation-task-force/labels/Stream

**Comment by elf-pavlik** [comment]
:+1: 6 :-1: 0 I will transfer issues now
