### ISSUE TITLE
Query Interface

### ISSUE THREAD

**Issue by rubensworks** [rdfjs/data-model-spec#167]
As pointed out in #166, there is a need for a separate query-specific spec.

This would enable functionality like:
* Cardinality estimation: https://github.com/rdfjs/data-model-spec/issues/166
* Pushing down filters: https://github.com/rdfjs/stream-spec/issues/17
* ...

Unless there are any major concerns against this, I would suggest creating a separate repo (`query-engine-spec`) to initiate this effort.

**Comment by jacoscaz** [comment]
I whole-heartedly support this!

**Comment by jacoscaz** [comment]
With `quadstore@7.0.1-alpha.5` we got a first iteration of pushing filters down to the persistence level to work correctly and pass all tests.

Based on that, I think that the query interface could do well with focusing on being a low-level interface and offering a purely-declarative, pipeline-like way to describe queries (I have omitted RDF/JS-specific language for clarity):

```
const pipeline = [
  { type: ‘bgp’, pattern: { predicate: ‘ex:age’, object: ‘?a’ } },
  { type: ‘gte’, args: [‘?a’, ‘“21”^^xsd:int’] },
];
```

The generation of such a structure could be abstracted into a more idiomatic interface, in line with the rest of RDF/JS:

```
const pipeline = factory.pipeline(
  factory.match(
    null,
    factory.namedNode(‘ex:age‘),
    factory.variable(‘a’),
  ),
  factory.gte(
    factory.variable(‘a’),
    factory.literal(‘21’, factory.namedNode(‘xsd:int’)),
  ),
);
```

The declarative, pipeline-like shape facilitates:

1) passing queries to non-JS backends
2) looping through stages, re-ordering and aggregating them according to the optimization capabilities of specific implementations
3) adding support for new stages in later iterations of the query interface

Most of this is based on previous discussion with @bergos and @rubensworks . I’ve just been putting some of those ideas into practice to evaluate their viability and get more familiar with them before pushing the discussion forward.

**Comment by rubensworks** [comment]
Oh, very nice!

A pipeline-based architecture is interested, I hadn't thought of that before.
I'm just wondering if it's expressive enough for all types of queries.
I would suspect recursive filter definitions may be a bit more expressive, which is what SPARQL algebra does.

------

I'll look into setting up a dedicated repo, since there don't seem to be any concerns against it.

**Comment by rubensworks** [comment]
I've created a [new repo](https://github.com/rdfjs/query-spec/), let's use the issue tracker there for proposing concrete things.
