### ISSUE TITLE
Create a primer with detailed examples

### ISSUE THREAD

**Issue by bergos** [rdfjs/data-model-spec#46]
A primer should be created with detailed examples. See [rdfjs primer](https://github.com/zazukoians/rdfjs-primer/)

**Comment by dmitrizagidulin** [comment]
Ohh man, this would be amazing :)

**Comment by pieroit** [comment]
I can produce some examples on the classes included in the UML, and later on the streaming part which is still difficult to me (#45 is really important). What do you think of an informal style like this:
http://pieroit.org/portfolio/linked-data-grandma/
Maybe a little more serious, but not too much. :)
And a few pictures, they are key to speed up learning.

**Comment by elf-pavlik** [comment]
If someone wants to create a primer we should just create a dedicated repo for it. Preferably one would start it in personal repo and then propose transferring it to this orga.
